version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: xtylo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: xtylo
      POSTGRES_PASSWORD: xtylo_pass
      POSTGRES_DB: xtylo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
